/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package jsdt.action.login;

import java.io.IOException;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import jsdt.model.User;
import jsdt.tools.Util;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 03-11-2011
 * 
 * XDoclet definition:
 * @struts.action parameter="op" validate="true"
 */
public class LoginTyAction extends DispatchAction {
	Logger log=Logger.getLogger(LoginTyAction.class);
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws UnsupportedEncodingException {
        ActionForward forward=null;
		response.setContentType("text/html; charset=utf-8");
		request.setCharacterEncoding("utf-8");
		HttpSession session = request.getSession();

		String username = request.getParameter("username");
		String password1 = request.getParameter("password");
		System.out.println(username);
		User user = new User(username);
		int sid = user.getSid();
		if (sid == 0) {
			request.setAttribute("errorMsg", "没有该用户！");
			forward= mapping.findForward("error");
		} else {
			int status = user.getStatus();
			if (status == 0) {
				request.setAttribute("errorMsg", "用户已注销！");
				forward= mapping.findForward("error");
			} else {
				String password = user.getPassword();
				if (!password.equals(Util.tomd5(password1))) {
					request.setAttribute("errorMsg", "输入密码错误");
					forward= mapping.findForward("error");
				} else {
					String yhswjgbm = user.getSwjgbm();
					String userMenu = user.selectUserMenu(username);
					session.setAttribute("userMenu", userMenu);
					session.setAttribute("userid", sid);
					session.setAttribute("username", username);
					session.setAttribute("yhswjgbm", yhswjgbm);
					session.setAttribute("czyswjgbm", yhswjgbm);
					session.setAttribute("yhcxswjgbmStr", "'" + yhswjgbm + "'");
					session.setAttribute("yhswjgbmStr", "'" + yhswjgbm + "'");
					System.out.println(yhswjgbm);
					System.out.println(username);
					forward= mapping.findForward("success");
				}
			}
		}
		return forward;
	}

	public ActionForward toLoginOut(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		HttpSession session = request.getSession();
		session.removeAttribute("userMenu");
		session.removeAttribute("userid");
		session.removeAttribute("username");
		session.removeAttribute("yhswjgbm");
		session.invalidate();
	 
		response.sendRedirect("/javaskweb/logout.success.jsp");
		return null;

	}

}